// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRunner.Infrastructure.ConnectionStrings;

#nullable disable

namespace TRunner.Infrastructure.Migrations
{
    [DbContext(typeof(TRunnerDbContext))]
    partial class TRunnerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GroupSport", b =>
                {
                    b.Property<int>("GroupsGroupId")
                        .HasColumnType("int");

                    b.Property<int>("SportsSportId")
                        .HasColumnType("int");

                    b.HasKey("GroupsGroupId", "SportsSportId");

                    b.HasIndex("SportsSportId");

                    b.ToTable("GroupSport");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<int>("GroupsGroupId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("GroupsGroupId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("GroupUser");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("GroupImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GroupTypeId")
                        .HasColumnType("int");

                    b.Property<string>("GroupUUId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("IsPublished")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<int>("TotalRunner")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.HasKey("GroupId");

                    b.HasIndex("GroupTypeId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.GroupType", b =>
                {
                    b.Property<int>("GroupTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GroupTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GroupTypeUUId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("GroupTypeId");

                    b.ToTable("GroupType");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("longtext");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.Sport", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SportTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SportUUId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SportId");

                    b.HasIndex("SportTypeId");

                    b.ToTable("Sport");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.SportType", b =>
                {
                    b.Property<int>("SportTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("SportTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SportTypeUUId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SportTypeId");

                    b.ToTable("SportType");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("IsRunner")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("double");

                    b.HasKey("UserId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserRoleUUId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.ViewPermissionType", b =>
                {
                    b.Property<int>("ViewPermissionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ViewPermission")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ViewPermissionTypeUUId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ViewPermissionTypeId");

                    b.ToTable("ViewPermissionType");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.WorkoutDetailByTime", b =>
                {
                    b.Property<int>("WorkoutDetailByTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkoutDetailData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WorkoutSummaryId")
                        .HasColumnType("int");

                    b.HasKey("WorkoutDetailByTimeId");

                    b.HasIndex("WorkoutSummaryId")
                        .IsUnique();

                    b.ToTable("WorkoutDetailByTime");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.WorkoutImage", b =>
                {
                    b.Property<int>("WorkoutImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkoutImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WorkoutSummaryId")
                        .HasColumnType("int");

                    b.HasKey("WorkoutImageId");

                    b.HasIndex("WorkoutSummaryId");

                    b.ToTable("WorkoutImage");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.WorkoutSummary", b =>
                {
                    b.Property<int>("WorkoutSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("AvgSpeed")
                        .HasColumnType("double");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<double>("Distance")
                        .HasColumnType("double");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.Property<int>("ViewPermissionTypeId")
                        .HasColumnType("int");

                    b.HasKey("WorkoutSummaryId");

                    b.HasIndex("SportId");

                    b.HasIndex("UserRoleId");

                    b.HasIndex("ViewPermissionTypeId");

                    b.ToTable("WorkoutSummary");
                });

            modelBuilder.Entity("GroupSport", b =>
                {
                    b.HasOne("TRunner.Domain.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRunner.Domain.Entities.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportsSportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("TRunner.Domain.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRunner.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TRunner.Domain.Entities.Group", b =>
                {
                    b.HasOne("TRunner.Domain.Entities.GroupType", "GroupType")
                        .WithMany("Groups")
                        .HasForeignKey("GroupTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupType");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TRunner.Domain.Entities.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TRunner.Domain.Entities.Sport", b =>
                {
                    b.HasOne("TRunner.Domain.Entities.SportType", "SportType")
                        .WithMany("Sports")
                        .HasForeignKey("SportTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportType");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.User", b =>
                {
                    b.HasOne("TRunner.Domain.Entities.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.WorkoutDetailByTime", b =>
                {
                    b.HasOne("TRunner.Domain.Entities.WorkoutSummary", "WorkoutSummary")
                        .WithOne("WorkoutDetailByTime")
                        .HasForeignKey("TRunner.Domain.Entities.WorkoutDetailByTime", "WorkoutSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSummary");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.WorkoutImage", b =>
                {
                    b.HasOne("TRunner.Domain.Entities.WorkoutSummary", "WorkoutSummary")
                        .WithMany("WorkoutImages")
                        .HasForeignKey("WorkoutSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSummary");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.WorkoutSummary", b =>
                {
                    b.HasOne("TRunner.Domain.Entities.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRunner.Domain.Entities.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRunner.Domain.Entities.ViewPermissionType", "ViewPermissionType")
                        .WithMany("WorkoutSummaries")
                        .HasForeignKey("ViewPermissionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");

                    b.Navigation("UserRole");

                    b.Navigation("ViewPermissionType");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.GroupType", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.SportType", b =>
                {
                    b.Navigation("Sports");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.ViewPermissionType", b =>
                {
                    b.Navigation("WorkoutSummaries");
                });

            modelBuilder.Entity("TRunner.Domain.Entities.WorkoutSummary", b =>
                {
                    b.Navigation("WorkoutDetailByTime")
                        .IsRequired();

                    b.Navigation("WorkoutImages");
                });
#pragma warning restore 612, 618
        }
    }
}
